version: '2'
services:
  tomcat1:
    expose:
      - "9090"
    build: tomcat1/.
  tomcat2:
    expose:
      - "9090"
    build: tomcat2/.
  httpd:
    volumes:
      - ./logs:/var/log/apache2
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    build: httpd/.
    links:
      - tomcat1:tomcat1
      - tomcat2:tomcat2
